# Generated by Django 5.0.14 on 2026-07-06 14:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami quyidagi formatda bo'lishi kerak: +998901234567", regex='^\\+998\\d{9}$')], verbose_name='telefon raqami')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='ism')),
                ('is_active', models.BooleanField(default=True, verbose_name='faolmi')),
                ('is_staff', models.BooleanField(default=False, verbose_name='xodimmi')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="ro'yxatdan o'tgan vaqti")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, verbose_name='viloyat')),
                ('district', models.CharField(max_length=100, verbose_name='tuman')),
                ('street', models.CharField(max_length=255, verbose_name="ko'cha, uy")),
                ('landmark', models.CharField(blank=True, max_length=255, verbose_name="mo'ljal")),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqami quyidagi formatda bo'lishi kerak: +998901234567", regex='^\\+998\\d{9}$')], verbose_name='aloqa uchun telefon')),
                ('is_default', models.BooleanField(default=False, verbose_name='asosiy manzilmi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Manzil',
                'verbose_name_plural': 'Manzillar',
                'ordering': ['-is_default', 'id'],
            },
        ),
    ]
