# Generated by Django 5.2.15 on 2026-07-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_user_birth_date_user_email_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonus_points',
            field=models.PositiveIntegerField(default=0, verbose_name='bonus ballari'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_email',
            field=models.BooleanField(default=True, verbose_name='Email xabarlarga rozilik'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_sms',
            field=models.BooleanField(default=True, verbose_name='SMS xabarlarga rozilik'),
        ),
    ]
