# Generated by Django 5.0.14 on 2026-07-06 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nomi')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='faolmi')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='ota-kategoriya')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nomi')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='tavsif')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='narx')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='chegirmagacha narx')),
                ('width', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='kengligi (sm)')),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='balandligi (sm)')),
                ('depth', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='chuqurligi (sm)')),
                ('material', models.CharField(blank=True, choices=[('yogoch', "Yog'och"), ('ldsp', 'LDSP'), ('metall', 'Metall'), ('mato', 'Mato'), ('teri', 'Teri')], max_length=20, verbose_name='material')),
                ('room_type', models.CharField(blank=True, choices=[('mehmonxona', 'Mehmonxona'), ('yotoqxona', 'Yotoqxona'), ('oshxona', 'Oshxona'), ('ofis', 'Ofis'), ('bolalar_xonasi', 'Bolalar xonasi')], max_length=20, verbose_name='xona turi')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name="og'irligi (kg)")),
                ('stock', models.IntegerField(default=0, verbose_name='ombordagi qoldiq')),
                ('is_available', models.BooleanField(default=True, verbose_name='sotuvdami')),
                ('is_featured', models.BooleanField(default=False, verbose_name="bosh sahifada ko'rsatilsinmi")),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name="ko'rilganlar soni")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='kategoriya')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50, verbose_name='rang nomi')),
                ('color_hex', models.CharField(max_length=7, verbose_name='HEX kod')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/colors/', verbose_name='rasm')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='catalog.product', verbose_name='mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot rangi',
                'verbose_name_plural': 'Mahsulot ranglari',
                'ordering': ['color_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='rasm')),
                ('is_main', models.BooleanField(default=False, verbose_name='asosiy rasmmi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib raqami')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot rasmi',
                'verbose_name_plural': 'Mahsulot rasmlari',
                'ordering': ['order'],
            },
        ),
    ]
