# Generated by Django 5.2.15 on 2026-07-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, max_length=50, verbose_name='kichik sarlavha')),
                ('title', models.CharField(max_length=200, verbose_name='sarlavha')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='fon rasmi')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='tugma matni')),
                ('button_link', models.CharField(blank=True, max_length=200, verbose_name='tugma havolasi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='faolmi')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
                'ordering': ['order'],
            },
        ),
    ]
