# Generated by Django 5.2.15 on 2026-07-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_material_roomtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slides/', verbose_name='fon rasmi'),
        ),
    ]
