# Generated by Django 5.0.14 on 2026-07-06 14:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ism')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqami quyidagi formatda bo'lishi kerak: +998901234567", regex='^\\+998\\d{9}$')], verbose_name='telefon')),
                ('region', models.CharField(max_length=100, verbose_name='viloyat')),
                ('district', models.CharField(max_length=100, verbose_name='tuman')),
                ('address', models.CharField(max_length=255, verbose_name='manzil')),
                ('delivery_type', models.CharField(choices=[('tashkent', 'Toshkent ichi'), ('viloyat', 'Viloyat'), ('pickup', 'Olib ketish')], max_length=20, verbose_name='yetkazib berish turi')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='jami summa')),
                ('status', models.CharField(choices=[('yangi', 'Yangi'), ('tasdiqlangan', 'Tasdiqlangan'), ('yolda', "Yo'lda"), ('yetkazildi', 'Yetkazildi'), ('bekor_qilingan', 'Bekor qilingan')], default='yangi', max_length=20, verbose_name='holat')),
                ('payment_status', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('tolangan', "To'langan"), ('bekor', 'Bekor')], default='kutilmoqda', max_length=20, verbose_name="to'lov holati")),
                ('payment_method', models.CharField(choices=[('naqd', "Naqd — yetkazib berishda to'lov")], default='naqd', max_length=20, verbose_name="to'lov usuli")),
                ('comment', models.TextField(blank=True, verbose_name='izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='rang')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='narx (buyurtma paytida)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='miqdor')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='buyurtma')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='mahsulot')),
            ],
            options={
                'verbose_name': 'Buyurtma qatori',
                'verbose_name_plural': 'Buyurtma qatorlari',
            },
        ),
    ]
