# Generated by Django 5.2.15 on 2026-07-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='promokod')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='izoh')),
                ('discount_type', models.CharField(choices=[('foiz', 'Foiz (%)'), ('summa', "Belgilangan summa (so'm)")], default='foiz', max_length=10, verbose_name='chegirma turi')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='chegirma qiymati')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Foizli chegirma uchun eng yuqori summa (ixtiyoriy).', max_digits=12, null=True, verbose_name='maksimal chegirma (faqat foiz uchun)')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='minimal buyurtma summasi')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='amal boshlanishi')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='amal tugashi')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text="Bo'sh qoldirilsa — cheksiz.", null=True, verbose_name='umumiy foydalanish limiti')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='foydalanilgan soni')),
                ('is_active', models.BooleanField(default=True, verbose_name='faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
            ],
            options={
                'verbose_name': 'Promokod',
                'verbose_name_plural': 'Promokodlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='chegirma summasi'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, max_length=30, verbose_name="qo'llanilgan promokod"),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='jami summa (chegirmadan keyin)'),
        ),
    ]
